name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ goodi ]   # פרוס כשדוחפים ל-goodi
  workflow_dispatch: {}    # וגם אפשר להריץ ידנית

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."        # מגיש את כל ה-root של הריפו (app.html וכו')

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
