name: Goodi Agent DL

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 9 * * *"   # 12:00 בישראל (UTC+3 בקיץ → 09:00 UTC)
    - cron: "0 13 * * *"  # 16:00 בישראל בקיץ

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      GOODI_USER: ${{ secrets.GOODI_USER }}
      GOODI_PASS: ${{ secrets.GOODI_PASS }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        working-directory: goodi_agent_dl
        run: npm ci

      - name: Download Goodi report (today)
        working-directory: goodi_agent_dl
        run: npm run start

      - name: Parse & insert to Supabase
        working-directory: goodi_agent_dl
        run: npm run parse
